# Rails container currently needs to be restarted after the docker-compose is brought up, as it depends on the mysql service which takes more than 15 seconds to start.
version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: docker/Dockerfile.rails
    command: bash docker/rails_entry.sh
    environment:
      BUNDLE_PATH: "/bundle"
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
      SOLR_HOST: solr
      SOLR_PORT: 8983
      # Need to pass the user running docker into the container so that
      # config/admin_usernames.yml pulls in the user as an admin. This is
      # to replicate existing behavior on OSX and may not work correctly on
      # another OS
      USER: #{USER}
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - solr