# Rails container currently needs to be restarted after the docker-compose is brought up, as it depends on the mysql service which takes more than 15 seconds to start.
#
# To look at the Rails logs for development:
# $ docker exec -t medieval_micro_rails_1 cat log/development.log
#
# To spin down the Rails application:
# $ docker-compose down --remove-orphans
version: '3.2'
services:
  rails:
    build:
      context: .
      dockerfile: docker/Dockerfile.rails
    command: bash docker/rails_entry.sh
    environment:
      BUNDLE_PATH: "/bundle"
      MYSQL_HOST: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SOLR_HOST: solr
      SOLR_PORT: 8983
      # Need to pass the user running docker into the container so that
      # config/admin_usernames.yml pulls in the user as an admin. This is
      # to replicate existing behavior on OSX and may not work correctly on
      # another OS
      USER: #{USER}
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - solr
