# To start Solr and MySQL as background daemon: docker-compose up -d
# To also start up the rails app as background daemon: docker-compose -f docker-compose.yml -f docker-compose-rails.yml up -d
# Both of the above commands run from the root of the repository
version: '3'
services:
  mysql:
    build:
      context: ./docker/
      dockerfile: Dockerfile.mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: medieval_development
    volumes:
      - ./docker/mysql-utf8.cnf:/etc/mysql/conf.d/mysql-utf8.cnf
    healthcheck:
        interval: 30s
        timeout: 10s
        retries: 5
  solr:
    build:
      context: .
      dockerfile: docker/Dockerfile.solr
    ports:
      - "8983:8983"