FROM nginx:1.17.9

RUN mkdir /project_root

COPY docker/wait-for-it.sh /project_root/wait-for-it.sh
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx_entry.sh /project_root/nginx_entry.sh